### ISSUE TITLE
Advice on usage

### ISSUE THREAD

**Issue by jpmurray** [adhocore/docker-lemp#15]
Hello!

Say I want to deploy in this docker image a repo I have hosted somewhere, what would you recommend ?

- `git clone` from inside the nginx image, or;
- cloning outside of the docker image and linking the folder to the nginx public directory?

**Comment by adhocore** [comment]
this lemp stack is not meant for production deployment but dev only

it is not supposed to be cloned but pulled from docker to run the container either with or without docker-compose.

usage info: https://github.com/adhocore/docker-lemp#usage

**Comment by jpmurray** [comment]
Well, seems I can't write anymore, because above question is missing an important words:

> Say I want to deploy **some code base**

I want to know how you'd put your projet's code you're working on in dev! :)

**Comment by adhocore** [comment]
by volume mapping your project root to /var/www/html which can be done with or without docker-compose.
if you use docker-compose recommended to commit docker-compose.yml in your project root dir.
the usage and example is given in readme docs of this project.
