### ISSUE TITLE
php8

### ISSUE THREAD

**Issue by Kabingeran** [adhocore/docker-lemp#20]
Hi!
I think it's great to add php 8

**Comment by adhocore** [comment]
yes i was thinking about it too

**Comment by adhocore** [comment]
need pecl first : `https://github.com/docker-library/php/issues/1050`

**Comment by adhocore** [comment]
here you go for 8.0beta:
https://github.com/adhocore/docker-lemp/tree/8.0b

**Comment by adhocore** [comment]
also there is rc already:
https://github.com/adhocore/docker-lemp/tree/8.0rc
