### ISSUE TITLE
How to connect to mysql in the mirror through sequel pro during development

### ISSUE THREAD

**Issue by SummerMagic** [adhocore/docker-lemp#24]

**Comment by adhocore** [comment]
i think #22 or #23 might help

**Comment by SummerMagic** [comment]
# ./docker-compose.yml docker exec -it lemp sh
version: '3'

services:
  app:
    image: adhocore/lemp:7.4
    # For different app you can use different names. (eg: )
    container_name: lemp
    volumes:
      - db_data:/var/lib/mysql
      - /Users/magic/Code:/var/www/html
      - /Users/magic/docker/docker-lemp/nginx/conf.d:/etc/nginx/conf.d
      # Here you can also volume php ini settings
      # - /path/to/zz-overrides:/usr/local/etc/php/conf.d/zz-overrides.ini
    ports:
      - 80:80
      - 443:443
      - 6379:6379
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: app
      MYSQL_DATABASE: secret
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      # for postgres you can pass in similar env as for mysql but with PGSQL_ prefix

volumes:
  db_data: {}


　Sequel pro shows that the connection cannot be made to mysql redils-desktop 127.0.0.1:6379 127.0.0.1 3306 connection failed

**Comment by adhocore** [comment]
sequel pro is for redis or mysql? maybe try localhost instead of 127.0.0.1

**Comment by SummerMagic** [comment]
localhost connection to redis mysql in docker lemp also failed

**Comment by adhocore** [comment]
did you expose port correctly? and is the exposed port available in host system?

**Comment by SummerMagic** [comment]
This is my local configuration file 
80 443 Can be used normally

# ./docker-compose.yml docker exec -it lemp sh
version: '3'

services:
  app:
    image: adhocore/lemp:7.4
    # For different app you can use different names. (eg: )
    container_name: lemp
    volumes:
      - db_data:/var/lib/mysql
      - /Users/magic/Sdmonk:/var/www/html
      - /Users/magic/docker/docker-lemp/nginx/conf.d:/etc/nginx/conf.d
      # Here you can also volume php ini settings
      # - /path/to/zz-overrides:/usr/local/etc/php/conf.d/zz-overrides.ini
    ports:
      - 80:80
      - 443:443
      - 6379:6379
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD:root
      MYSQL_DATABASE: secret
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      # for postgres you can pass in similar env as for mysql but with PGSQL_ prefix

volumes:
  db_data: {}

**Comment by adhocore** [comment]
apologies i had to reply earlier. i don't use sequel pro so not sure if i could help any better.

(with adminer the exposed port works correctly, or in fact lemp itself is packaged with adminer)
