### ISSUE TITLE
Support for XDEBIG

### ISSUE THREAD

**Issue by gogl92** [adhocore/docker-lemp#25]
As a developer, I want to be able to debug my code.

**Comment by adhocore** [comment]
it is in 7.4 tag and during that time xdebug didnt get along well with php8

will add it in 8.0 tag as well

**Comment by adhocore** [comment]
oh actually it had been added already as pecl ext long ago

> https://github.com/adhocore/docker-phpfpm/blob/8.0/Dockerfile#L11

---
can be verified like this:
```sh
docker run adhocore/phpfpm:8.0 php -m | grep xdebug  # in fpm
docker run adhocore/lemp:8.0 php -m | grep xdebug    # in lemp
```

**Comment by adhocore** [comment]
closing ticket
