### ISSUE TITLE
Question to gd extension (JPEG and FreeType support)

### ISSUE THREAD

**Issue by rraab-dev** [adhocore/docker-lemp#26]
Hello,
nice work first of all! This image/container is just replacing XAMPP on my development environment.
One thing I did not get running fully was the GD extension.

Basically I want to achieve that phpinfo() returns in the gd section the following entries, which it does not yet:
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => x.x.x
JPEG Support => enabled
libJPEG Version => 9 compatible

How can I achieve this?
(I need to work with JPG images in my project, to add a watermark to an uploaded jpg image and save it.)

Thanks in advance

**Comment by adhocore** [comment]
maybe need to configure - (it might require some extra apk add for header files) - would you have some time to play around on it? thanks for opening issue

**Comment by adhocore** [comment]
yea like that - but if it is done in this container already  - then you dont have to run those in your Dockerfile.

as such this should now be done in https://github.com/adhocore/docker-phpfpm instead (which is base docker image for fpm)

**Comment by rraab-dev** [comment]
Haha okay I will try and let you know in your PayPal account when I surrendered.
Thanks for your time! :)

**Comment by rraab-dev** [comment]
Done, may you review it. :)
https://github.com/adhocore/docker-phpfpm/pull/35

**Comment by adhocore** [comment]
great and thanks, did you run docker build locally? (how about swoole downgrade) 😁

**Comment by rraab-dev** [comment]
nice yes I have built and run it locally (7.4 and 8.0.6 Version) and checkt with phpinf() and this extensions are now enabled.
I have not edited anything with swoole. :D

**Comment by adhocore** [comment]
ok i fixed that in newer commits https://github.com/adhocore/docker-phpfpm/commits/main

phpfpm is already built and lemp is builing https://hub.docker.com/r/adhocore/lemp/tags?page=1&ordering=last_updated 
you should be able to do `docker pull adhocore/lemp:8.0` and `docker pull adhocore/lemp:7.4` in about half an hour or less
