### ISSUE TITLE
Give an option to disable services via env variables and conditionals.

### ISSUE THREAD

**Issue by dgomesbr** [adhocore/docker-lemp#28]
Give an option to disable services via env variables and conditionals.

eg: Disabled Postgres, Disable Elasticsearch.

**Comment by adhocore** [comment]
ya that should be nice feature 😁

**Comment by adhocore** [comment]
`DISABLE=pgsql,memcached,...` will do the trick, [more docs](https://github.com/adhocore/docker-lemp#disabling-services)
