### ISSUE TITLE
Copy Application into container

### ISSUE THREAD

**Issue by gogl92** [adhocore/docker-lemp#31]
Sometimes a full containerized app needs to be created to easily ship to a service or to give to someone for testing, how to achieve this? The only way I found is to add this line to the `Dockerfile`:

```
# Copy source code
COPY --chown=www-data:www-data . /var/www/html
```

**Comment by adhocore** [comment]
yep that, or if the recipient is somewhat techie could as well send the app repo (github/bitbucket etc) and the `Dockerfile` or even better `docker-compose.yml` (with volumes preconfigured)  and some instructions to run it

**Comment by gogl92** [comment]
@adhocore but the other thing is I'd like to deploy this to AWS/Google cloud so it'd be easier just to create a container with the code already loaded

**Comment by adhocore** [comment]
yes then COPY in Dockerfile
