### ISSUE TITLE
ARM SUPPORT

### ISSUE THREAD

**Issue by yourjhay** [adhocore/docker-lemp#34]
Hoping to support linux/arm64/v8

like RPI 4 or arm base devices

**Comment by adhocore** [comment]
ok i will see what i can do sometime next week. pls ping if i take long.

**Comment by adhocore** [comment]
i have tried to fix it in the base phpfpm https://github.com/adhocore/docker-phpfpm/issues/81#issuecomment-1500765128,
if that works out, i will update here for lemp as well

**Comment by adhocore** [comment]
should be fixed by 9597abb68cdd456742472c6eaa263655e7365f60
