### ISSUE TITLE
Suggestion: Rename folder php to `webapp` or `project` or similar

### ISSUE THREAD

**Issue by gogl92** [adhocore/docker-lemp#36]
When I try to containerize my own project I have to store in a different place the `php-fpm.ini` that is inside the `php` folder , delete the index.php, copy my code into the php folder and add back the `php-fpm.ini`, I feel like the structure should be more like:

```text
root 
       --- php 
             --- php-fpm.ini
       --- webapp
             --- index.php (or the files of the project to be containerized) 
```

In this structure we keep the php config files in a different location than the php code files.

so that in the Dockerfiles we can copy all the files inside the project folder, so instead of 

```
COPY php/index.php /var/www/html/index.php
```

we can do something like

```
COPY ./php/. /var/www/html/
```

to copy all the files

**Comment by adhocore** [comment]
oh actually that is just the path for lemp stack not the application source code. the index.php is just a default landing page to show "it works". the actual app should instead directly volume map to /var/www/html. hope this helps. :)

**Comment by gogl92** [comment]
@adhocore oh got it, the way I use this project is: I clone the project put the code of my project in the PHP folder and then build the docker image then I distribute the image to the frontend devs or submit it to Google cloud to deploy it into an instance for the QA team, I know maybe this isn't the intention of the repo but it has been working for us.
