### ISSUE TITLE
How to set up a virtualhost?

### ISSUE THREAD

**Issue by faridmovsumov** [adhocore/docker-lemp#37]
Is this possible to set up a virtualhost for the project?

For example instead of running project on http://localhost:8080/ I would like to run on example.local

**Comment by adhocore** [comment]
yes if you have nginx running in host context.

you can create custom host in nginx conf to [proxy_pass](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/) to localhost:8080.
you might also need to have that host in local dns mapping `/etc/hosts` (unix) or `C:\Windows\System32\drivers\etc\hosts` (win)
