### ISSUE TITLE
add ssl (https) support

### ISSUE THREAD

**Issue by adhocore** [adhocore/docker-lemp#4]

**Comment by moltolegato** [comment]
I'm pretty sure this is meant to be a local testing environment only, there is no need for ssl support.

**Comment by adhocore** [comment]
correct. it was not for localhost. but some virtual local host eg. .lvh.me
probably using self signed certificate but not sure if that is worth it

**Comment by moltolegato** [comment]
Unless it is an absolute requirement to use ssl, I suggest developing without it. Your the only one who has access to it, so it shouldn't really matter. As long as your using ssl when you launch the real website your good to go.

**Comment by adhocore** [comment]
yes, but sometimes it is desirable to run in SSL while developing for certain reasons
for now im closing this issue unresolved.
