### ISSUE TITLE
What about Phalcon? 

### ISSUE THREAD

**Issue by borisdelev** [adhocore/docker-lemp#41]
Sorry if not the place, but... What about Phalcon? Can be included somehow?

Thank you!

**Comment by adhocore** [comment]
it used to be in base fpm image (https://github.com/adhocore/docker-phpfpm) but removed later with a notice:
> **Important Note**: To be able to support arm builds (https://github.com/adhocore/docker-phpfpm/issues/81) we removed some big and slow to compile extensions like swoole/grpc/phalcon for now. Check [example](https://github.com/adhocore/docker-phpfpm#extensions) below how to add them back in your images based off on adhcore/phpfpm.

**Comment by adhocore** [comment]
i hope you could setup by referring to the example snippet above
