### ISSUE TITLE
Add adminer or phpmyadmin

### ISSUE THREAD

**Issue by adhocore** [adhocore/docker-lemp#5]

**Comment by abiusx** [comment]
Do you need help with this? Or is it functional?

**Comment by adhocore** [comment]
> is it functional?

not yet. i think i would like to go with `adminer` for its simplicity and tiny footprint

> Do you need help with this?

would be great! and thanks :+1: 

i was thinking of downloading adminer (if it doesnt exist or is 30 days too old) like so:
then configure nginx to set docroot for `/adminer` to `/var/www/adminer/` instead of `/var/www/html/`

```sh
ADMINER=/var/www/adminer/index.php
if [[ !-f $ADMINER ]] || [[ $(find "$ADMINER" -mtime +30 -print) ]]; then
  curl -sSLo $ADMINER $(curl -s https://api.github.com/repos/vrana/adminer/releases/latest | grep 'browser_download_url.*\d-en.php' -m 1 | cut -d : -f 2,3 | tr -d \" \ )
fi
```
would be nice if you continue this idea or even anything better ;)

**Comment by abiusx** [comment]
I have done that much but the problem is with the socket. Why do you use a socket for MySQL instead of normal port on localhost? That makes it harder on everything!

**Comment by adhocore** [comment]
ok i will check how mysql can be contacted with localhost:3306

**Comment by abiusx** [comment]
Thanks! Please update me whne you know. Good job btw.

**Comment by adhocore** [comment]
should now be possible to do:
```php
$db = new PDO(
    'mysql:host=127.0.0.1;port=3306;dbname=' . getenv('MYSQL_DATABASE'),
    getenv('MYSQL_USER'),
    getenv('MYSQL_PASSWORD')
);
```

pls update it by running `docker pull adhocore/lemp` first

**Comment by adhocore** [comment]
i think #7 is also useful feature

**Comment by abiusx** [comment]
Good job!
I think adding redis to it would also be a good idea. I rarely use mailcatcher though.

**Comment by adhocore** [comment]
i have finished setting up adminer. will commit and release asap.

**Comment by adhocore** [comment]
added adminer (http:/localhost:8080/adminer) and postgres.
(`docker pull adhocore/lemp`)

**Comment by adhocore** [comment]
redis has been added too
