### ISSUE TITLE
SSL certificate configuration

### ISSUE THREAD

**Issue by gogl92** [adhocore/docker-lemp#50]
I've been using this image to test on my staging instances, sometimes the frontend apps need https connection so I have to manually get into the instance and request a certificate using certbot, maybe it'd be easier if the nginx SSL configuration is available within the image so when I boot the container it can pull the certificates and keys.

nginx/conf.d/default-ssl.conf

```
server {
  listen 80;
  listen [::]:80 ipv6only=on default_server;
  server_name _;

  # Redirect HTTP to HTTPS
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  listen [::]:443 ssl ipv6only=on default_server;
  server_name _;

  ssl_certificate /etc/ssl/certs/certificate.pem;
  ssl_certificate_key /etc/ssl/private/certificate.key;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers HIGH:!aNULL:!MD5;

  index index.php index.html index.htm;

  set $docroot "html";
  if (-d "/var/www/html/public") {
    set $docroot "html/public";
  }
  if ($request_filename ~ /adminer) {
    set $docroot "adminer";
  }

  root "/var/www/${docroot}";

  if (!-e $request_filename) {
    rewrite ^.*$ /index.php last;
  }

  location ~ \.php$ {
    fastcgi_pass 0.0.0.0:9000;
    fastcgi_index index.php;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_param PATH_INFO $fastcgi_path_info;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_buffers 16 16k;
    fastcgi_buffer_size 32k;
    include fastcgi_params;
  }

  location ~ /\.ht {
    deny all;
  }
}
```

**Comment by adhocore** [comment]
hi @gogl92 after long :D 

since this all-in-one lemp itself is designed for local/dev usage and cert is hostname specific and there is no standard path as to where cert is located, i guess not practical/feasible to include ssl related config. if you are having to repeat things i think it can be an idea to have a custom docker entrypoint do it for you, also you can have the custom ssl-aware nginx-conf volume mapped to container's version

**Comment by gogl92** [comment]
Hello @adhocore I know long time no see xD,  I understand yeah maybe I can add the custom entry point and add the volume of the certificate, thanks tho.
