### ISSUE TITLE
Migrate from adminer to AdminerEvo

### ISSUE THREAD

**Issue by gogl92** [adhocore/docker-lemp#51]
Adminer seems to be an abandoned project and I've been getting these warnings

![image](https://github.com/user-attachments/assets/536ac286-1554-49d7-a7a1-f42ce8199d6c)

A good option well maintained is:
https://github.com/adminerevo/adminerevo

I still need to check other lightweight database browser viewer/editor.

(sorry I can't keep for opening issues lol)

**Comment by adhocore** [comment]
@gogl92 thank you for bringing it to attention. since i am not actively using php myself these days, i think i would have to depend on you or any community contributor for replacing adminer with adminerevo, will merge the PR as soon as i notice it

**Comment by gogl92** [comment]
Happy to help, I'll create the PR, thank you

**Comment by gogl92** [comment]
@adhocore yay, The PR was merged! but the pipeline failed, I'm not sure if related.

https://github.com/adhocore/docker-lemp/actions/runs/10771092163/job/29865873629

**Comment by adhocore** [comment]
build is successful, test has failed maybe some ports are not open i.e some services may not be running or has changed default port

(not related to adminer)
